modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "animatedtrims"
version = "${version}"
displayName = "AnimatedTrims"
authors = "Bawnorton"
description = '''
A mod that adds animated trim materials to the game.
'''
#logoFile = ""

[[dependencies.animatedtrims]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animatedtrims]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.animatedtrims]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"